export const HEROES = [
  { id:'superman', attackType:'beam', name:'Superman', universe:'DC', role:'Vanguard', hp:700, speed:7.4, damage:38, fireRate:0.34, range:22, color:0x2878ff, primary:'Heat Vision', ability:'Solar Rush', abilityKind:'dash', abilityCooldown:5, secondary:'Freeze Breath', secondaryKind:'slowBurst', secondaryCooldown:7, ultimate:'Worldbreaker', ultKind:'slam' },
  { id:'wonder-woman', attackType:'melee', meleeRadius:6.5, name:'Wonder Woman', universe:'DC', role:'Vanguard', hp:650, speed:7.2, damage:42, fireRate:0.42, range:7, color:0xd94b52, primary:'Godkiller Strikes', ability:'Aegis Guard', abilityKind:'shield', abilityCooldown:7, secondary:'Shield Throw', secondaryKind:'heavyProjectile', secondaryCooldown:5, ultimate:'Amazon Fury', ultKind:'empower' },
  { id:'batman', attackType:'projectile', projectileSpeed:31, name:'Batman', universe:'DC', role:'Duelist', hp:360, speed:8.2, damage:31, fireRate:0.20, range:19, color:0x424a62, primary:'Batarang', ability:'Grapnel Burst', abilityKind:'blink', abilityCooldown:6, secondary:'Explosive Batarang', secondaryKind:'heavyProjectile', secondaryCooldown:5, ultimate:'Fear Protocol', ultKind:'stun' },
  { id:'flash', attackType:'melee', meleeRadius:5.5, name:'The Flash', universe:'DC', role:'Duelist', hp:325, speed:10.5, damage:26, fireRate:0.14, range:6, color:0xe03838, primary:'Speed Strikes', ability:'Speed Force Dash', abilityKind:'dash', abilityCooldown:3, secondary:'Phase Step', secondaryKind:'phase', secondaryCooldown:6, ultimate:'Infinite Mass', ultKind:'slam' },
  { id:'green-lantern', attackType:'projectile', projectileSpeed:29, name:'Green Lantern', universe:'DC', role:'Strategist', hp:400, speed:7.5, damage:29, fireRate:0.25, range:24, color:0x35e783, primary:'Power Ring', ability:'Construct Shield', abilityKind:'teamShield', abilityCooldown:8, secondary:'Energy Cage', secondaryKind:'rootBurst', secondaryCooldown:8, ultimate:'Emerald Army', ultKind:'teamHeal' },
  { id:'raven', attackType:'projectile', projectileSpeed:25, name:'Raven', universe:'DC', role:'Strategist', hp:360, speed:7.1, damage:30, fireRate:0.28, range:22, color:0x8a66d9, primary:'Soul Bolt', ability:'Soul Bind', abilityKind:'heal', abilityCooldown:6, secondary:'Dark Passage', secondaryKind:'phase', secondaryCooldown:7, ultimate:'Azarath', ultKind:'teamHeal' },

  { id:'thanos', attackType:'melee', meleeRadius:7.5, name:'Thanos', universe:'Marvel', role:'Vanguard', hp:780, speed:6.7, damage:46, fireRate:0.45, range:9, color:0x7251a8, primary:'Titan Fist', ability:'Titan Charge', abilityKind:'dash', abilityCooldown:6, secondary:'Brutal Throw', secondaryKind:'knockbackBurst', secondaryCooldown:7, ultimate:'Infinity Surge', ultKind:'slam' },
  { id:'juggernaut', attackType:'melee', meleeRadius:6.5, name:'Juggernaut', universe:'Marvel', role:'Vanguard', hp:760, speed:6.9, damage:44, fireRate:0.40, range:6, color:0x9b3b32, primary:'Crimson Fists', ability:'Unstoppable', abilityKind:'shield', abilityCooldown:7, secondary:'Ground Breaker', secondaryKind:'knockbackBurst', secondaryCooldown:6, ultimate:'Crimson Impact', ultKind:'slam' },
  { id:'doctor-doom', attackType:'projectile', projectileSpeed:27, name:'Doctor Doom', universe:'Marvel', role:'Duelist', hp:430, speed:7.0, damage:36, fireRate:0.24, range:25, color:0x4c8d68, primary:'Arc Bolt', ability:'Arcane Barrage', abilityKind:'burst', abilityCooldown:6, secondary:'Gauntlet Beam', secondaryKind:'heavyBeam', secondaryCooldown:5, ultimate:'Doom Protocol', ultKind:'empower' },
  { id:'gorr', attackType:'melee', meleeRadius:8.5, name:'Gorr the God Butcher', universe:'Marvel', role:'Duelist', hp:420, speed:7.8, damage:40, fireRate:0.26, range:11, color:0xdadada, primary:'Necrosword', ability:'Necrosword Lunge', abilityKind:'dash', abilityCooldown:4, secondary:'Necrospear', secondaryKind:'heavyProjectile', secondaryCooldown:5, ultimate:'Black Berserker', ultKind:'empower' },
  { id:'silver-surfer', attackType:'projectile', projectileSpeed:34, name:'Silver Surfer', universe:'Marvel', role:'Strategist', hp:390, speed:8.6, damage:30, fireRate:0.22, range:27, color:0xc9d2dc, primary:'Cosmic Bolt', ability:'Cosmic Renewal', abilityKind:'heal', abilityCooldown:5, secondary:'Cosmic Beam', secondaryKind:'heavyBeam', secondaryCooldown:5, ultimate:'Power Cosmic', ultKind:'teamHeal' },
  { id:'professor-x', attackType:'projectile', projectileSpeed:26, name:'Professor X', universe:'Marvel', role:'Strategist', hp:330, speed:6.1, damage:25, fireRate:0.32, range:26, color:0x5576c7, primary:'Psychic Lance', ability:'Psychic Barrier', abilityKind:'teamShield', abilityCooldown:8, secondary:'Mental Command', secondaryKind:'selfHaste', secondaryCooldown:8, ultimate:'Cerebral Lock', ultKind:'stun' },
  xport const HEROES = [
  { id:'superman', attackType:'beam', name:'Superman', universe:'DC', role:'Vanguard', hp:700, speed:7.4, damage:38, fireRate:0.34, range:22, color:0x2878ff, primary:'Heat Vision', ability:'Solar Rush', abilityKind:'dash', abilityCooldown:5, secondary:'Freeze Breath', secondaryKind:'slowBurst', secondaryCooldown:7, ultimate:'Worldbreaker', ultKind:'slam' },
  { id:'wonder-woman', attackType:'melee', meleeRadius:6.5, name:'Wonder Woman', universe:'DC', role:'Vanguard', hp:650, speed:7.2, damage:42, fireRate:0.42, range:7, color:0xd94b52, primary:'Godkiller Strikes', ability:'Aegis Guard', abilityKind:'shield', abilityCooldown:7, secondary:'Shield Throw', secondaryKind:'heavyProjectile', secondaryCooldown:5, ultimate:'Amazon Fury', ultKind:'empower' },
  { id:'batman', attackType:'projectile', projectileSpeed:31, name:'Batman', universe:'DC', role:'Duelist', hp:360, speed:8.2, damage:31, fireRate:0.20, range:19, color:0x424a62, primary:'Batarang', ability:'Grapnel Burst', abilityKind:'blink', abilityCooldown:6, secondary:'Explosive Batarang', secondaryKind:'heavyProjectile', secondaryCooldown:5, ultimate:'Fear Protocol', ultKind:'stun' },
  { id:'flash', attackType:'melee', meleeRadius:5.5, name:'The Flash', universe:'DC', role:'Duelist', hp:325, speed:10.5, damage:26, fireRate:0.14, range:6, color:0xe03838, primary:'Speed Strikes', ability:'Speed Force Dash', abilityKind:'dash', abilityCooldown:3, secondary:'Phase Step', secondaryKind:'phase', secondaryCooldown:6, ultimate:'Infinite Mass', ultKind:'slam' },
  { id:'green-lantern', attackType:'projectile', projectileSpeed:29, name:'Green Lantern', universe:'DC', role:'Strategist', hp:400, speed:7.5, damage:29, fireRate:0.25, range:24, color:0x35e783, primary:'Power Ring', ability:'Construct Shield', abilityKind:'teamShield', abilityCooldown:8, secondary:'Energy Cage', secondaryKind:'rootBurst', secondaryCooldown:8, ultimate:'Emerald Army', ultKind:'teamHeal' },
  { id:'raven', attackType:'projectile', projectileSpeed:25, name:'Raven', universe:'DC', role:'Strategist', hp:360, speed:7.1, damage:30, fireRate:0.28, range:22, color:0x8a66d9, primary:'Soul Bolt', ability:'Soul Bind', abilityKind:'heal', abilityCooldown:6, secondary:'Dark Passage', secondaryKind:'phase', secondaryCooldown:7, ultimate:'Azarath', ultKind:'teamHeal' },

  { id:'thanos', attackType:'melee', meleeRadius:7.5, name:'Thanos', universe:'Marvel', role:'Vanguard', hp:780, speed:6.7, damage:46, fireRate:0.45, range:9, color:0x7251a8, primary:'Titan Fist', ability:'Titan Charge', abilityKind:'dash', abilityCooldown:6, secondary:'Brutal Throw', secondaryKind:'knockbackBurst', secondaryCooldown:7, ultimate:'Infinity Surge', ultKind:'slam' },
  { id:'juggernaut', attackType:'melee', meleeRadius:6.5, name:'Juggernaut', universe:'Marvel', role:'Vanguard', hp:760, speed:6.9, damage:44, fireRate:0.40, range:6, color:0x9b3b32, primary:'Crimson Fists', ability:'Unstoppable', abilityKind:'shield', abilityCooldown:7, secondary:'Ground Breaker', secondaryKind:'knockbackBurst', secondaryCooldown:6, ultimate:'Crimson Impact', ultKind:'slam' },
  { id:'doctor-doom', attackType:'projectile', projectileSpeed:27, name:'Doctor Doom', universe:'Marvel', role:'Duelist', hp:430, speed:7.0, damage:36, fireRate:0.24, range:25, color:0x4c8d68, primary:'Arc Bolt', ability:'Arcane Barrage', abilityKind:'burst', abilityCooldown:6, secondary:'Gauntlet Beam', secondaryKind:'heavyBeam', secondaryCooldown:5, ultimate:'Doom Protocol', ultKind:'empower' },
  { id:'gorr', attackType:'melee', meleeRadius:8.5, name:'Gorr the God Butcher', universe:'Marvel', role:'Duelist', hp:420, speed:7.8, damage:40, fireRate:0.26, range:11, color:0xdadada, primary:'Necrosword', ability:'Necrosword Lunge', abilityKind:'dash', abilityCooldown:4, secondary:'Necrospear', secondaryKind:'heavyProjectile', secondaryCooldown:5, ultimate:'Black Berserker', ultKind:'empower' },
  { id:'silver-surfer', attackType:'projectile', projectileSpeed:34, name:'Silver Surfer', universe:'Marvel', role:'Strategist', hp:390, speed:8.6, damage:30, fireRate:0.22, range:27, color:0xc9d2dc, primary:'Cosmic Bolt', ability:'Cosmic Renewal', abilityKind:'heal', abilityCooldown:5, secondary:'Cosmic Beam', secondaryKind:'heavyBeam', secondaryCooldown:5, ultimate:'Power Cosmic', ultKind:'teamHeal' },
  { id:'professor-x', attackType:'projectile', projectileSpeed:26, name:'Professor X', universe:'Marvel', role:'Strategist', hp:330, speed:6.1, damage:25, fireRate:0.32, range:26, color:0x5576c7, primary:'Psychic Lance', ability:'Psychic Barrier', abilityKind:'teamShield', abilityCooldown:8, secondary:'Mental Command', secondaryKind:'selfHaste', secondaryCooldown:8, ultimate:'Cerebral Lock', ultKind:'stun' },
  { id:'kang', attackType:'projectile', projectileSpeed:30, name:'Kang', universe:'Marvel', role:'Duelist', hp:390, speed:7.2, damage:34, fireRate:0.24, range:24, color:0x5d55ae, primary:'Temporal Rifle', ability:'Temporal Shift', abilityKind:'blink', abilityCooldown:6, ultimate:'Chrono Collapse', ultKind:'stun' }
];

export const getHero = id => HEROES.find(h => h.id === id) || HEROES[0];
