export const HEROES = [
  { id:'superman', attackType:'beam', name:'Superman', universe:'DC', role:'Vanguard', hp:700, speed:7.4, damage:38, fireRate:0.34, range:22, color:0x2878ff, primary:'Heat Vision', secondary:'Freeze Breath', secondaryKind:'slowBurst', secondaryCooldown:7, ability:'Solar Flight', abilityKind:'dash', abilityCooldown:5, ultimate:'Worldbreaker', ultKind:'slam' },
  { id:'wonder-woman', attackType:'melee', meleeRadius:6.5, name:'Wonder Woman', universe:'DC', role:'Vanguard', hp:650, speed:7.2, damage:42, fireRate:0.42, range:7, color:0xd94b52, primary:'Godkiller Strikes', secondary:'Shield Throw', secondaryKind:'heavyProjectile', secondaryCooldown:5, ability:'Aegis Guard', abilityKind:'shield', abilityCooldown:7, ultimate:'Amazon Fury', ultKind:'empower' },
  { id:'batman', attackType:'projectile', projectileSpeed:31, name:'Batman', universe:'DC', role:'Duelist', hp:360, speed:8.2, damage:31, fireRate:0.20, range:19, color:0x424a62, primary:'Batarang', secondary:'Explosive Batarang', secondaryKind:'heavyProjectile', secondaryCooldown:5, ability:'Grapnel Launch', abilityKind:'blink', abilityCooldown:6, ultimate:'Fear Protocol', ultKind:'stun' },
  { id:'flash', resourceKind:'speedForce', resourceLabel:'SPEED FORCE', attackType:'melee', meleeRadius:5.5, name:'The Flash', universe:'DC', role:'Duelist', hp:325, speed:10.5, damage:26, fireRate:0.14, range:6, color:0xe03838, primary:'Speed Strikes', secondary:'Phase Step', secondaryKind:'phase', secondaryCooldown:6, ability:'Speed Force Dash', abilityKind:'dash', abilityCooldown:3, ultimate:'Infinite Mass', ultKind:'slam' },
  { id:'green-lantern', attackType:'projectile', projectileSpeed:29, name:'Green Lantern', universe:'DC', role:'Strategist', hp:400, speed:7.5, damage:29, fireRate:0.25, range:24, color:0x35e783, primary:'Power Ring', secondary:'Energy Cage', secondaryKind:'rootBurst', secondaryCooldown:8, ability:'Construct Shield', abilityKind:'teamShield', abilityCooldown:8, ultimate:'Emerald Army', ultKind:'teamHeal' },
  { id:'raven', attackType:'projectile', projectileSpeed:25, name:'Raven', universe:'DC', role:'Strategist', hp:360, speed:7.1, damage:30, fireRate:0.28, range:22, color:0x8a66d9, primary:'Soul Bolt', secondary:'Dark Passage', secondaryKind:'phase', secondaryCooldown:7, ability:'Soul Bind', abilityKind:'heal', abilityCooldown:6, ultimate:'Azarath', ultKind:'teamHeal' },

  { id:'thanos', attackType:'melee', meleeRadius:7.5, name:'Thanos', universe:'Marvel', role:'Vanguard', hp:780, speed:6.7, damage:46, fireRate:0.45, range:9, color:0x7251a8, primary:'Titan Fist', secondary:'Brutal Throw', secondaryKind:'knockbackBurst', secondaryCooldown:7, ability:'Titan Charge', abilityKind:'dash', abilityCooldown:6, ultimate:'Infinity Surge', ultKind:'slam' },
  { id:'juggernaut', resourceKind:'momentum', resourceLabel:'MOMENTUM', attackType:'melee', meleeRadius:6.5, name:'Juggernaut', universe:'Marvel', role:'Vanguard', hp:760, speed:6.9, damage:44, fireRate:0.40, range:6, color:0x9b3b32, primary:'Crimson Fists', secondary:'Ground Breaker', secondaryKind:'knockbackBurst', secondaryCooldown:6, ability:'Unstoppable', abilityKind:'shield', abilityCooldown:7, ultimate:'Crimson Impact', ultKind:'slam' },
  { id:'doctor-doom', resourceKind:'arcaneCharge', resourceLabel:'ARCANE CHARGE', attackType:'projectile', projectileSpeed:27, name:'Doctor Doom', universe:'Marvel', role:'Duelist', hp:430, speed:7.0, damage:36, fireRate:0.24, range:25, color:0x4c8d68, primary:'Arc Bolt', secondary:'Gauntlet Beam', secondaryKind:'heavyBeam', secondaryCooldown:5, ability:'Arcane Barrage', abilityKind:'burst', abilityCooldown:6, ultimate:'Doom Protocol', ultKind:'empower' },
  { id:'gorr', resourceKind:'hatred', resourceLabel:'HATRED', attackType:'melee', meleeRadius:8.5, name:'Gorr the God Butcher', universe:'Marvel', role:'Duelist', hp:420, speed:7.8, damage:40, fireRate:0.26, range:11, color:0xdadada, primary:'Necrosword', secondary:'Necrospear', secondaryKind:'heavyProjectile', secondaryCooldown:5, ability:'Necrosword Lunge', abilityKind:'dash', abilityCooldown:4, ultimate:'Black Berserker', ultKind:'empower' },
  { id:'silver-surfer', resourceKind:'powerCosmic', resourceLabel:'POWER COSMIC', attackType:'projectile', projectileSpeed:34, name:'Silver Surfer', universe:'Marvel', role:'Strategist', hp:390, speed:8.6, damage:30, fireRate:0.22, range:27, color:0xc9d2dc, primary:'Cosmic Bolt', secondary:'Cosmic Beam', secondaryKind:'heavyBeam', secondaryCooldown:5, ability:'Cosmic Renewal', abilityKind:'heal', abilityCooldown:5, ultimate:'Power Cosmic', ultKind:'teamHeal' },
  { id:'professor-x', attackType:'projectile', projectileSpeed:26, name:'Professor X', universe:'Marvel', role:'Strategist', hp:330, speed:6.1, damage:25, fireRate:0.32, range:26, color:0x5576c7, primary:'Psychic Lance', secondary:'Mental Command', secondaryKind:'selfHaste', secondaryCooldown:8, ability:'Psychic Barrier', abilityKind:'teamShield', abilityCooldown:8, ultimate:'Cerebral Lock', ultKind:'stun' },
  { id:'kang', resourceKind:'temporalCharge', resourceLabel:'TEMPORAL CHARGE', attackType:'projectile', projectileSpeed:30, name:'Kang', universe:'Marvel', role:'Duelist', hp:390, speed:7.2, damage:34, fireRate:0.24, range:24, color:0x5d55ae, primary:'Temporal Rifle', secondary:'Chrono Burst', secondaryKind:'slowBurst', secondaryCooldown:7, ability:'Temporal Shift', abilityKind:'blink', abilityCooldown:6, ultimate:'Chrono Collapse', ultKind:'stun' },

  { id:'aquaman', attackType:'melee', meleeRadius:7, name:'Aquaman', universe:'DC', role:'Vanguard', hp:640, speed:7.1, damage:41, fireRate:0.38, range:8, color:0x1aa69a, primary:'Trident Strikes', secondary:'Tidal Burst', secondaryKind:'knockbackBurst', secondaryCooldown:6, ability:'Atlantean Guard', abilityKind:'shield', abilityCooldown:7, ultimate:'King of Atlantis', ultKind:'slam' },
  { id:'cyborg', attackType:'projectile', projectileSpeed:32, name:'Cyborg', universe:'DC', role:'Strategist', hp:430, speed:7.0, damage:31, fireRate:0.23, range:25, color:0x8fa6b8, primary:'Sonic Cannon', secondary:'Target Lock', secondaryKind:'heavyBeam', secondaryCooldown:6, ability:'Team Uplink', abilityKind:'teamShield', abilityCooldown:8, ultimate:'Grid Overdrive', ultKind:'teamHeal' },
  { id:'nightwing', attackType:'melee', meleeRadius:5.8, name:'Nightwing', universe:'DC', role:'Duelist', hp:350, speed:8.8, damage:29, fireRate:0.18, range:6, color:0x2e8fd8, primary:'Escrima Combo', secondary:'Wing-Ding', secondaryKind:'heavyProjectile', secondaryCooldown:5, ability:'Acrobat Rush', abilityKind:'dash', abilityCooldown:4, ultimate:'Bludhaven Blitz', ultKind:'empower' },
  { id:'starfire', attackType:'projectile', projectileSpeed:33, name:'Starfire', universe:'DC', role:'Duelist', hp:390, speed:8.0, damage:35, fireRate:0.24, range:25, color:0xe88343, primary:'Starbolt', secondary:'Solar Flare', secondaryKind:'slowBurst', secondaryCooldown:7, ability:'Tamaranean Rush', abilityKind:'dash', abilityCooldown:5, ultimate:'Nova Crown', ultKind:'empower' },
  { id:'deathstroke', attackType:'projectile', projectileSpeed:38, name:'Deathstroke', universe:'DC', role:'Duelist', hp:410, speed:7.7, damage:34, fireRate:0.21, range:27, color:0xe87832, primary:'Tactical Rifle', secondary:'Sword Rush', secondaryKind:'knockbackBurst', secondaryCooldown:6, ability:'Combat Roll', abilityKind:'dash', abilityCooldown:4, ultimate:'Perfect Contract', ultKind:'empower' },
  { id:'harley-quinn', attackType:'projectile', projectileSpeed:30, name:'Harley Quinn', universe:'DC', role:'Duelist', hp:340, speed:8.3, damage:30, fireRate:0.19, range:21, color:0xe35a87, primary:'Mayhem Pistol', secondary:'Pop Gun', secondaryKind:'heavyProjectile', secondaryCooldown:5, ability:'Mallet Vault', abilityKind:'dash', abilityCooldown:5, ultimate:'Carnival Chaos', ultKind:'stun' },
  { id:'joker', attackType:'projectile', projectileSpeed:28, name:'Joker', universe:'DC', role:'Strategist', hp:360, speed:7.4, damage:28, fireRate:0.25, range:22, color:0x7bc34a, primary:'Trick Pistol', secondary:'Laughing Gas', secondaryKind:'slowBurst', secondaryCooldown:7, ability:'False Gift', abilityKind:'heal', abilityCooldown:7, ultimate:'One Bad Day', ultKind:'stun' },
  { id:'martian-manhunter', attackType:'beam', name:'Martian Manhunter', universe:'DC', role:'Strategist', hp:480, speed:7.4, damage:31, fireRate:0.29, range:24, color:0x4aaa78, primary:'Martian Vision', secondary:'Phase Form', secondaryKind:'phase', secondaryCooldown:7, ability:'Telepathic Guard', abilityKind:'teamShield', abilityCooldown:8, ultimate:'Mind of Mars', ultKind:'stun' },
  { id:'shazam', attackType:'melee', meleeRadius:6.8, name:'Shazam', universe:'DC', role:'Vanguard', hp:650, speed:7.6, damage:42, fireRate:0.36, range:7, color:0xd9433b, primary:'Champion Strikes', secondary:'Living Lightning', secondaryKind:'heavyBeam', secondaryCooldown:6, ability:'Mercury Rush', abilityKind:'dash', abilityCooldown:5, ultimate:'Power of Shazam', ultKind:'empower' },
  { id:'black-adam', attackType:'projectile', projectileSpeed:30, name:'Black Adam', universe:'DC', role:'Vanguard', hp:660, speed:7.5, damage:40, fireRate:0.31, range:21, color:0x2b2f36, primary:'Lightning Bolt', secondary:'Judgment', secondaryKind:'slowBurst', secondaryCooldown:7, ability:'Ancient Guard', abilityKind:'shield', abilityCooldown:7, ultimate:'Kahndaq Fury', ultKind:'slam' },
  { id:'zatanna', attackType:'projectile', projectileSpeed:27, name:'Zatanna', universe:'DC', role:'Strategist', hp:350, speed:7.3, damage:28, fireRate:0.26, range:24, color:0x6e5db6, primary:'Arcane Cards', secondary:'Backward Spell', secondaryKind:'rootBurst', secondaryCooldown:8, ability:'Mystic Renewal', abilityKind:'heal', abilityCooldown:6, ultimate:'Finale', ultKind:'teamHeal' },
  { id:'constantine', attackType:'projectile', projectileSpeed:26, name:'John Constantine', universe:'DC', role:'Strategist', hp:360, speed:7.0, damage:29, fireRate:0.27, range:23, color:0xb89b63, primary:'Hellblazer Hex', secondary:'Binding Sigil', secondaryKind:'rootBurst', secondaryCooldown:8, ability:'Ward Circle', abilityKind:'teamShield', abilityCooldown:8, ultimate:'Devils Due', ultKind:'stun' },

  { id:'ghost-rider', attackType:'melee', meleeRadius:8, name:'Ghost Rider', universe:'Marvel', role:'Duelist', hp:440, speed:8.1, damage:39, fireRate:0.27, range:10, color:0xff7a22, primary:'Hellchain', secondary:'Hellfire', secondaryKind:'slowBurst', secondaryCooldown:6, ability:'Infernal Rush', abilityKind:'dash', abilityCooldown:5, ultimate:'Penance Stare', ultKind:'stun' },
  { id:'cyclops', attackType:'beam', name:'Cyclops', universe:'Marvel', role:'Duelist', hp:370, speed:7.4, damage:35, fireRate:0.22, range:30, color:0xe65444, primary:'Optic Blast', secondary:'Wide Beam', secondaryKind:'heavyBeam', secondaryCooldown:5, ability:'Blast Step', abilityKind:'dash', abilityCooldown:5, ultimate:'Full Power', ultKind:'empower' },
  { id:'nightcrawler', attackType:'melee', meleeRadius:5.7, name:'Nightcrawler', universe:'Marvel', role:'Duelist', hp:330, speed:9.0, damage:29, fireRate:0.17, range:6, color:0x3542a4, primary:'Twin Blades', secondary:'Bamf Strike', secondaryKind:'phase', secondaryCooldown:5, ability:'Teleport', abilityKind:'blink', abilityCooldown:4, ultimate:'Bamf Assault', ultKind:'slam' },
  { id:'rogue', attackType:'melee', meleeRadius:6.5, name:'Rogue', universe:'Marvel', role:'Vanguard', hp:610, speed:7.7, damage:40, fireRate:0.34, range:7, color:0x4b9d57, primary:'Power Punch', secondary:'Drain Touch', secondaryKind:'selfHaste', secondaryCooldown:8, ability:'Southern Rush', abilityKind:'dash', abilityCooldown:5, ultimate:'Power Surge', ultKind:'empower' },
  { id:'iceman', attackType:'projectile', projectileSpeed:28, name:'Iceman', universe:'Marvel', role:'Strategist', hp:380, speed:7.5, damage:28, fireRate:0.24, range:24, color:0x72c9ef, primary:'Ice Shard', secondary:'Deep Freeze', secondaryKind:'slowBurst', secondaryCooldown:6, ability:'Ice Armor', abilityKind:'shield', abilityCooldown:7, ultimate:'Absolute Zero', ultKind:'stun' },
  { id:'gambit', attackType:'projectile', projectileSpeed:36, name:'Gambit', universe:'Marvel', role:'Duelist', hp:350, speed:8.2, damage:33, fireRate:0.20, range:25, color:0xd85ac8, primary:'Kinetic Cards', secondary:'Charged Staff', secondaryKind:'knockbackBurst', secondaryCooldown:6, ability:'Cajun Dash', abilityKind:'dash', abilityCooldown:4, ultimate:'Royal Flush', ultKind:'slam' },
  { id:'vision', attackType:'beam', name:'Vision', universe:'Marvel', role:'Strategist', hp:430, speed:7.4, damage:31, fireRate:0.27, range:25, color:0xb04952, primary:'Mind Beam', secondary:'Density Shift', secondaryKind:'phase', secondaryCooldown:7, ability:'Solar Shield', abilityKind:'teamShield', abilityCooldown:8, ultimate:'Synthetic Ascension', ultKind:'teamHeal' },
  { id:'carnage', attackType:'melee', meleeRadius:7.2, name:'Carnage', universe:'Marvel', role:'Duelist', hp:390, speed:8.7, damage:36, fireRate:0.19, range:8, color:0xb51f2e, primary:'Symbiote Blades', secondary:'Tendril Burst', secondaryKind:'knockbackBurst', secondaryCooldown:6, ability:'Frenzy Lunge', abilityKind:'dash', abilityCooldown:4, ultimate:'Maximum Carnage', ultKind:'empower' },
  { id:'ultron', attackType:'projectile', projectileSpeed:31, name:'Ultron', universe:'Marvel', role:'Strategist', hp:420, speed:7.2, damage:30, fireRate:0.23, range:26, color:0x9aa1a8, primary:'Encephalo Beam', secondary:'Drone Barrage', secondaryKind:'heavyProjectile', secondaryCooldown:6, ability:'Repair Protocol', abilityKind:'heal', abilityCooldown:6, ultimate:'Ultron Network', ultKind:'teamHeal' },
  { id:'apocalypse', attackType:'projectile', projectileSpeed:27, name:'Apocalypse', universe:'Marvel', role:'Vanguard', hp:720, speed:6.8, damage:43, fireRate:0.36, range:19, color:0x5d6f93, primary:'Celestial Blast', secondary:'Molecular Shift', secondaryKind:'selfHaste', secondaryCooldown:8, ability:'Celestial Armor', abilityKind:'shield', abilityCooldown:7, ultimate:'Survival of the Fittest', ultKind:'empower' }
];

export const getHero = id => HEROES.find(h => h.id === id) || HEROES[0];
